amazonProperties:
  accessKey: AKIAINIQZBYM72Z3CUPA
  secretKey: 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

amazonStorageProperties:
  endpointUrl: https://s3.us-west-2.amazonaws.com
  bucketName: rsi-memes

amazonRdsProperties:
  driver: com.mysql.cj.jdbc.Driver
  dbName: RSI_memes_west
  endpoint: rsi-memes-west.cc3u1nwicnba.us-east-2.rds.amazonaws.com
  port: 3306
  region: us-east-2a
  username: RSI_memes_west
  password: 20JAs18!
