amazonProperties:
  accessKey: XXXXXXXXXXXXXXXXXXXX
  secretKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

amazonStorageProperties:
  endpointUrl: https://s3.us-west-2.amazonaws.com
  bucketName: rsi-memes

amazonRdsProperties:
  driver: com.mysql.cj.jdbc.Driver
  dbName: XXXXXXXXX
  hostname: rsi-memes.cvdjwayq6x4k.us-west-2.rds.amazonaws.com
  region: us-west-2a
  port: 3306
  username: XXXXXXXXX
  password: XXXXXXXXX
